
### Create USER
POST http://localhost:3000/users/auth/signup
content-Type: : application/json

{
    "email":"ratzpereira@gmail.com",
    "password":"sdsdsdsdsd"
}
### GEt user by id
GET http://localhost:3000/users/auth/3


###GET ALL BY EMAIL
GET http://localhost:3000/users/auth/ratzpereira@gmail.com


###UPDATE USER
PATCH http://localhost:3000/users/auth/1
content-Type: : application/json

{
    "email":"ratzpereira@gmail.com",
    "password":"1"
}